Import('env')
import os

debug = ARGUMENTS.get('debug',0)
target = "Ipsec_Transport"

BASE = env['BASE']
libs = env['LIBS']
lib_paths = env['LIBPATH']

TransportLib_path = os.path.join(BASE,'..','lib','libTransport')
TransportLib_include = os.path.join(BASE,'..','lib')
BOOSTLib_include = os.path.join(BASE,'..','thirdparty','boost_1_58_0')
BOOSTLib_libs = os.path.join(BASE,'..','thirdparty','boost_1_58_0','lib')
GLib_include = os.path.join(BASE,'..','thirdparty','gtest-1.7.0','include')
BOOSTSys_include = '/usr/include'

lib_paths.extend(['./TransportProto',BOOSTLib_libs,'/usr/local/lib',TransportLib_path])

if int(debug):
   env['CCFLAGS'] = [ \
                     '-Wall','-p','-g','-pthread','-std=c++0x', \
                     '-DBOOST_LOG_DYN_LINK','-I'+TransportLib_include, \
                     '-I'+BOOSTLib_include,'-I'+BOOSTSys_include, \
                     '-DBOOST_SYSTEM_NO_DEPRECATED','-DDEBUG_BUILD','-I'+GLib_include \
                    ]
else:
   env['CCFLAGS'] = [ \
                     '-Wall','-pthread','-O3','-std=c++0x', \
                     '-DBOOST_LOG_DYN_LINK','-I'+TransportLib_include, \
                     '-I'+BOOSTLib_include,'-I'+BOOSTSys_include, \
                     '-DBOOST_SYSTEM_NO_DEPRECATED','-I'+GLib_include \
                    ]

lg_boost = File(BOOSTLib_libs+'/libboost_log.a')
lg_boost_setup = File(BOOSTLib_libs+'/libboost_log_setup.a')

libs.extend(['libTransport','libprotoLib','protobuf', \
             lg_boost_setup,lg_boost,'boost_filesystem', \
            'boost_chrono','boost_date_time','boost_regex', \
            'boost_thread','boost_system','pthread'])

env['LIBS'] = libs


env.Program(target,Glob("*.c*"),LIBPATH=lib_paths)
